version: '3.9'
services:
  caddy:
    container_name: caddy
    image: caddy
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - web

  web:
    container_name: covid-app
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  caddy: